import { Roboto } from 'next/font/google'
 
const roboto = Roboto({
  weight: '700',
  subsets: ['latin'],
  display: 'swap',
})
import "./globals.css";
import Navbar from "./componentes/Navbar";
import Footer from './componentes/Footer';

 

export const metadata = {
  title: "Website Nextjs  ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={roboto.className}>
      <Navbar />
        {children}
        <Footer/>
        </body>
    </html>
  );
}
